version: '3.8'

services:
  app:
    build: .
    container_name: books_app
    ports:
      - "80:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/Books

  mongo:
    image: mongo:6
    container_name: books_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
